import './globals.css';
import type { Metadata } from 'next';
import LayoutDefault from '@/layouts';
import { ThemeProvider } from 'next-themes';
import { Toaster } from '@/components/ui/sonner';
import { QueryProvider } from '@/provider/query-provider'
import { Geist, Geist_Mono, Montserrat } from 'next/font/google';
import AIChatbox from '@/components/ai-chatbox';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} font-montserrat`}>                                                                    
        <ThemeProvider
          attribute="class"
          storageKey="next_theme"
          defaultTheme="light"
          enableColorScheme={false}
          enableSystem={false}
        >
          <Toaster position="top-right" />
          <QueryProvider>
            <LayoutDefault>{children}</LayoutDefault>
          </QueryProvider>
          <AIChatbox />
        </ThemeProvider>
      </body>
    </html>
  );
}
